apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: kafkaanomalies.kafka.strimzi.io
  labels:
    app: strimzi
    strimzi.io/crd-install: "true"
spec:
  group: kafka.strimzi.io
  names:
    kind: KafkaAnomaly
    listKind: KafkaAnomalyList
    singular: kafkaanomaly
    plural: kafkaanomalies
    shortNames:
    - ka
    categories:
    - strimzi
  scope: Namespaced
  conversion:
    strategy: None
  versions:
  - name: v1beta2
    served: true
    storage: true
    subresources:
      status: {}
    additionalPrinterColumns:
    - name: ID
      description: Anomaly ID
      jsonPath: .spec.anomalyId
      type: string
    - name: Type
      description: Anomaly type
      jsonPath: .spec.anomalyType
      type: string
    - name: Autofix
      description: Autofix triggered
      jsonPath: .spec.autoFixTriggered
      type: string
    - name: Time
      description: Self-healing start time
      jsonPath: .spec.selfHealingStartTime
      type: integer
    - name: Action
      description: Action result
      jsonPath: .spec.action
      type: string
    schema:
      openAPIV3Schema:
        type: object
        properties:
          apiVersion:
            type: string
            description: "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources"
          kind:
            type: string
            description: "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds"
          metadata:
            type: object
          spec:
            type: object
            properties:
              anomalyId:
                type: string
                description: AnomalyId.
              anomalyType:
                type: string
                description: AnomalyType.
              autoFixTriggered:
                type: boolean
                description: AutoFixTriggered.
              selfHealingStartTime:
                type: integer
                description: SelfHealingStartTime.
              action:
                type: string
                description: Action.
            description: The specification of the Kafka anomaly.
          status:
            type: object
            properties:
              conditions:
                type: array
                items:
                  type: object
                  properties:
                    type:
                      type: string
                      description: "The unique identifier of a condition, used to distinguish between other conditions in the resource."
                    status:
                      type: string
                      description: "The status of the condition, either True, False or Unknown."
                    lastTransitionTime:
                      type: string
                      description: "Last time the condition of a type changed from one status to another. The required format is 'yyyy-MM-ddTHH:mm:ssZ', in the UTC time zone."
                    reason:
                      type: string
                      description: The reason for the condition's last transition (a single word in CamelCase).
                    message:
                      type: string
                      description: Human-readable message indicating details about the condition's last transition.
                description: List of status conditions.
              observedGeneration:
                type: integer
                description: The generation of the CRD that was last reconciled by the operator.
              progress:
                type: string
                description: Progress.
            description: The status of the Kafka anomaly.
